//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVIET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIVIET()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
        }
    
        public int IdBV { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string TacGia { get; set; }
        public string AnhBV { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string TrangThai { get; set; }
        public string Slide { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public int IdTaiKhoan { get; set; }
        public int IdTheLoai { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual THELOAIBAIVIET THELOAIBAIVIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
    }
}
