//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANBO
    {
        public int IdCB { get; set; }
        public string HoTen { get; set; }
        public string ChucVu { get; set; }
        public string BangCap { get; set; }
        public string Email { get; set; }
        public string QueQuan { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoDT { get; set; }
        public string AnhMoTa { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> IdTaiKhoan { get; set; }
        public Nullable<int> IdPhongBan { get; set; }
    
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
