//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int IdVideo { get; set; }
        public string TenVideo { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string LinkVideo { get; set; }
        public Nullable<int> IdAlbum { get; set; }
        public Nullable<int> IdTaiKhoan { get; set; }
    
        public virtual ALBUM ALBUM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
