//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Web_KTCKEntities : DbContext
    {
        public Web_KTCKEntities()
            : base("name=Web_KTCKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALBUM> ALBUMs { get; set; }
        public virtual DbSet<BAIVIET> BAIVIETs { get; set; }
        public virtual DbSet<BINHLUAN> BINHLUANs { get; set; }
        public virtual DbSet<CANBO> CANBOes { get; set; }
        public virtual DbSet<HINHANH> HINHANHs { get; set; }
        public virtual DbSet<LICHLAMVIEC> LICHLAMVIECs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TAILIEU> TAILIEUx { get; set; }
        public virtual DbSet<THELOAIBAIVIET> THELOAIBAIVIETs { get; set; }
        public virtual DbSet<THONGBAO> THONGBAOs { get; set; }
        public virtual DbSet<VIDEO> VIDEOs { get; set; }
    
        public virtual ObjectResult<RP_BaiViet_Result> RP_BaiViet(Nullable<int> iDBaiViet)
        {
            var iDBaiVietParameter = iDBaiViet.HasValue ?
                new ObjectParameter("IDBaiViet", iDBaiViet) :
                new ObjectParameter("IDBaiViet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RP_BaiViet_Result>("RP_BaiViet", iDBaiVietParameter);
        }
    }
}
